DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 1.0                   # 最大x前进速度，与TEB保持一致
  min_vel_x: 0.0                   # 最小x前进速度
  max_vel_y: 0.0                   # 最大y速度，全向移动机器人才用
  min_vel_y: 0.0                   # 最小y速度
  max_vel_trans: 1.0               # 最大平移速度
  min_vel_trans: 0.1               # 最小平移速度
  max_vel_theta: 1.0               # 最大角速度，与TEB保持一致
  min_vel_theta: 0.2               # 最小角速度
  acc_lim_x: 1.0                   # x加速度限制，与TEB保持一致
  acc_lim_y: 0.0                   # y加速度限制
  acc_lim_theta: 1.0               # 角加速度限制，与TEB保持一致

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.2           # 与TEB保持一致
  yaw_goal_tolerance: 0.1          # 与TEB保持一致
  latch_xy_goal_tolerance: false   

  # Forward Simulation Parameters
  sim_time: 2.0                    # 向前仿真轨迹的时间
  vx_samples: 20                   # x速度空间采样数
  vy_samples: 0                    # y速度空间采样数
  vth_samples: 40                  # 角速度空间采样数
  controller_frequency: 10.0       # 控制频率

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0         # 路径距离权重，影响贴近全局路径程度
  goal_distance_bias: 24.0         # 目标距离权重，影响朝目标直线前进程度
  occdist_scale: 0.01              # 障碍物距离权重，避障强度
  forward_point_distance: 0.325    # 前视点距离
  stop_time_buffer: 0.2            # 停止缓冲时间
  scaling_speed: 0.25              # 缩放速度的阈值
  max_scaling_factor: 0.2          # 最大缩放因子

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05     # 复位振荡状态的最小移动距离
  
  # Debugging
  publish_traj_pc: true            # 发布轨迹点云
  publish_cost_grid_pc: true       # 发布代价网格点云
  global_frame_id: odom            # 全局坐标系